### PR TITLE
Update to ES 2.2

### PR DESCRIPTION
**Pull request by masda70**
ES 2.2

Tests are passing, but I could not test Nominatim import and have not yet tested with some real data.
- References to FilterBuilder(s) changed to QueryBuilder(s) (Breaking API change in ES 2.0). Note that since `and`/`or` queries are now implemented via `bool`, some methods are now deprecated and should be updated before ES 3.0 (https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_query_dsl_changes.html).
- Updated `elasticsearch-wordending-tokenfilter-filter` to ES 2.2 (repo available at https://github.com/masda70/elasticsearch-wordending-tokenfilter)
- Groovy module installation now required for local node.
- Cleaned-up Postgis dependency (now only uses postgis-jts), otherwise ES throws a JarHell exception https://discuss.elastic.co/t/elasticsearch-2-0-java-api-jarhell-problems/34776
- Test gateway type is not NONE anymore (None throws an error).
- Removed `_id.path: id` from mapping.json (already deprecated in 1.x).
- Added `delete-by-query` plugin, which is needed for tests (https://www.elastic.co/guide/en/elasticsearch/plugins/2.2/plugins-delete-by-query.html)
- `name.similarity` and `collector.similarity` in `mappings.json` were throwing errors. Apparently, they were not properly defined (not doing anything). A similarity is now only defined for `collector.properties.default.similarity`, although I'm not sure if this want is needed.

### CODE REVIEW

**Comment by karussell** [comment]
Nice, thanks! When I have a bit more time I'll test Nominatim import with this.

**Comment by masda70** [comment]
I'm currently reindexing the 34GB dump with a variation of this branch (12% done). In the variation, I set the index default similarity to BM25. Currently for this pull, the similarity is only set for some fields, but I realized this was not coherent.

**Comment by christophlingg** [comment]
cool, looks solid

**Comment by christophlingg** [comment]
replaced by #219

**Comment by karussell** [comment]
I would prefer to testing this before and merge it separately.

**Comment by christophlingg** [comment]
perfect

**Comment by karussell** [comment]
Hmmh, having a hard time to get the uni tests working. It looks like the test dependencies are messed up and I get a lot of jar hell exceptions :/

The first problem is powermock-module-junit4 interfers with junit core somehow and the second is also related to postgres.

**Comment by karussell** [comment]
I've now exluded some dependencies:
```xml
<dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>            
        </dependency>
                
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>1.10.19</version>
            <scope>test</scope>
        </dependency>
                
                
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-module-junit4</artifactId>
            <version>1.6.4</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>org.powermock</groupId>
            <artifactId>powermock-api-mockito</artifactId>
            <version>1.6.4</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.mockito</groupId>
                    <artifactId>mockito-core</artifactId>
                </exclusion>                            
                <exclusion>
                    <groupId>org.hamcrest</groupId>
                    <artifactId>hamcrest-core</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
 and using a minor different jdbc version `9.1-901-1.jdbc4` but now I get problems with the deletebyquery plugin. It is downloaded several times and also the jar hell is throwed again

**Comment by reuschling** [comment]
I now made a related pull request for the ES 5 migration #254

**Comment by karussell** [comment]
I think we can close here in favor of #254 - thanks @masda70 for the work!

**Pull request closed without merging**
