### PR TITLE
Update to Elastic 8, use external cluster

### PR DESCRIPTION
**Pull request by alpoi-x**
This PR makes some major changes to support modern Elasticsearch, decoupling the cluster from import and search features. My company tasked me with adapting Photon such that we can host the cluster externally with [ElasticCloud](https://www.elastic.co/cloud). We now have this working in our dev environment, and plan to ship to production in the new year.

No expectations from me (it's a huge set of changes and will break any existing deployment), but I wanted to contribute nonetheless in-case you wanted to use or take ownership of any of the changes.

Being able to deploy externally on an updated ES version has been huge for us in terms of performance and cost. Hopefully it will be useful to others too!

*NB: tests probably broken*

### CODE REVIEW

**Comment by phamtai97** [comment]
Any update for PR? We also want to deploy external ES. Tks for your PR.

**Comment by lonvia** [comment]
This PR has mixed in too many other new features and is missing a solution for the tests. Those are blockers for merging. I'm leaving the PR open for now, given that ES 8 is requested a lot and people might want to play with it.

**Comment by phamtai97** [comment]
@lonvia Do you have plans to test this PR? I just fast review to changed files in this PR, I see the changes that seem do not related to logic search (indexes, change query logics).
@alpoi-x Do you list main ideas for your changes?

**Comment by lonvia** [comment]
Closing this, as we will go the OpenSearch route. Thank you for sharing your efforts.

**Pull request closed without merging**
