### PR TITLE
recursive formatting incl. organize imports

### LINKED ISSUE #278: Use common white spaces across the project
I'm against tabs (for no reason ;) !), so I would like to use 4 spaces and apply also the same code formatting to all source files. Currently we have a wild mix it seems.

Using the standard java rules stored in IntelliJ, see [this discussion](https://github.com/graphhopper/graphhopper/issues/770#issuecomment-246490515)

### PR DESCRIPTION
**Pull request by karussell**
Fixes #278

### CODE REVIEW

**Comment by karussell** [comment]
Looks like auto import cleanup did too much. Will fix the tests.

**Comment by lonvia** [comment]
That's quite large. But looks good so far. What do you think about adding a CONTRIBUTING.md with the styling rules to make it easier for contributors?

**Comment by karussell** [comment]
Yes, good idea.

Regarding the large changes: I did just one click in the IDE and the changes are sometimes not properly detected in the github diff so this is a bit confusing at some places.

**Comment by karussell** [comment]
> For this project, one single change like this one is better imho.

I think so too, because if just for touched files then there the changes are kind of invisible and so more error prone. This global reformatting (only to *.java btw) is automatically done and hopefully without a mistake :)

**Comment by karussell** [comment]
Have created this new contributing guide here https://github.com/komoot/photon/blob/master/.github/CONTRIBUTING.md - please feel free to edit&discuss it

**Pull request merged**
