### PR TITLE
Rework location bias and query builder in general

### PR DESCRIPTION
**Pull request by lonvia**
This is work in progress to improve the location bias for searches. As the unusually high boost for name queries was interfering with the location scoring, the query part itself needed to be reworked as well.

In detail:
* Location bias is switched to an exponential decay function with the given distance in kilometers as the 0.8 weight limit. To ensure that well-known places show up in the results nonetheless, use a second weight function based on importance and use the max of the two functions.
* Introduce a new parameter ' zoom'  for the location bias, which describes the radius for which the bias is effective as a function of the map zoom level. The precise relation is 0.25km*2^(18 - zoom). The `location_bias_scale` now describes how much weight is given to important places. Sensible values are between 0.0 and 1.0.
* Weight function for importance switched to a simple linear decay function. This essentially means using importance as a direct weight factor with the twist that it must not become completely zero.
* Reintroduce a subquery against the name.ngram index. This ensures similar results as the previous heavy boost on name.raw.
* Add a subquery against collector.raw which gets a strong boost when the house number matches. Records with housenumbers usually have no name (the street not being in the name indexes), so that they get a huge malus over name matches. The boost offsets this malus.

The query structure is still not ideal but any further improvements require a change to the index mapping. I would like to defer that until after the next release.

With the modified weight functions we might even be able to get rid of painless. That would be a huge relief.

There is a global test instance (using last weeks planet dump) with the changes running at https://pagan.lonvia.de/ Feedback would be very much appreciated.

@hbruch @leonardehrenfried

### CODE REVIEW

**Comment by lonvia** [comment]
Here are a couple of queries that still fail:

* https://pagan.lonvia.de/api?debug=1&q=alta (TF messes with the result)
* https://pagan.lonvia.de/api?q=Wien%20Lohwaggase%2010 (skipping a word ranks higher than typos)

**Comment by lonvia** [comment]
The latest commit fixes an issue where alternative names (`alt_name`, `old_name`, etc.) were not searchable anymore.

**Comment by kenseii** [comment]
@lonvia I think with the rework of the query builder searching with post code is no longer working. For example the results of `/api?q=289-1606` on the #585 PR(which is based on this PR) returns data totally different to the ones of photon.komoot.io which are quite accurate. Not sure if its a bug or if the support of post code search are going to be dropped.

**Comment by lonvia** [comment]
Postcode search has never really worked because we don't import the artificial postcode from Nominatim, see #310. Current master gives you some random result that would happen to have the postcode (a river in your example) but not really a postcode result. So I don't really see that as a regression.

**Comment by lonvia** [comment]
I've merged this now and deployed it on https://photon.komoot.io. We'll see if there is feedback from the wider user community.

**Pull request merged**
