### PR TITLE
Only shutdown if not starting API

### LINKED ISSUE #163: Photon doesn’t quit after import/dump actions
Currently, with Photon from commit 1abeb523, running the command below

    java -jar /photon/target/photon-0.2.3-SNAPSHOT.jar -nominatim-import -host localhost -port 5432 -database nominatim -user root -languages de

the following message is printed to the screen but Photon does not terminate.

    […]
    [main] INFO de.komoot.photon.nominatim.NominatimConnector - finished import of 927,553 photon documents.
    [main] INFO de.komoot.photon.App - imported data from nominatim to photon with languages: de

Reading issue #64, Photon should actually stop and reading Photon’s source code in file `App.java`, it should actually return.

                if(args.isNominatimImport()) {
                        startNominatimImport(args, esServer, esClient);
                        return;
                }

Could there be a problem with closing the connection to the database server or some other process?

### PR DESCRIPTION
**Pull request by karussell**
Should finally fix #163

### CODE REVIEW

**Comment by christophlingg** [comment]
what about writing `esServer.shutdown();` at the end of both if clauses? would save the try-catch  and the extra variable?

**Comment by karussell** [comment]
the try-finally clause makes shutting down ES even if an exception appear ... so under any circumstances. I think this is safer, although not that clean.

**Comment by karussell** [comment]
Ping :)
This is an important fix and I stumbled over this issue again (after merging the recent PR).

Let me know how you want this change!

**Comment by christophlingg** [comment]
sorry, i lost track of this pr

**Pull request merged**
