### PR TITLE
Fix #272: Add missing log4j2.xml to jar

### PR DESCRIPTION
**Pull request by hbruch**
Fix for #272

### CODE REVIEW

**Comment by karussell** [comment]
Thanks!

**Comment by marcosox** [comment]
Hi, I just downloaded the 0.3-alpha1 release and there is no `log4j2.xml` file, resulting in the usual `config file not found, logging only errors to the console etc. etc.` message.

**Comment by karussell** [comment]
This release is older than this fix

**Comment by RevanScript** [comment]
`ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging onl
y errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.l
evel' to TRACE to show Log4j2 internal initialization logging.`

is this related issue? when are you going to publish new jar? this one doesn't want to work :)

**Pull request merged**
