### PR TITLE
Upgrade to ES 1.4.4, replaced mvel with Groovy

### PR DESCRIPTION
**Pull request by karussell**
This PR contains two commits where first mvel was replaced with Groovy, then ES was upgraded to the latest 1.4.4. All test passed but didn't tested it yet in production or with the nominatim tests.

This PR fixes partially #151 

Still disabling dyncamic scripting in the config is to be done as we don't need it I think?

### CODE REVIEW

**Comment by christophlingg** [comment]
about the dynamic scripting, access to elasticsearch is only granted locally: https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/elasticsearch/Server.java#L71 I guess this is already sufficient in terms of security as you need access to the local machine.

however, disabling dynamic scripting is still a good option. you can hard code it for now or add a config file similar to what we already do with our scripts:
https://github.com/komoot/photon/blob/master/src/main/java/de/komoot/photon/elasticsearch/Server.java#L154

ref #151

**Comment by karussell** [comment]
Well, as I use more than one ES instance and the transport client this line is not sufficient :)

> add a config file similar to what we already do with our scripts:

yes

**Comment by karussell** [comment]
Also mvel seems to be stuck at 1.4.1 so it might be better to move to the default groovy

**Comment by karussell** [comment]
BTW: this fixes #145

**Comment by christophlingg** [comment]
ah ok, i thought you wanted to add the disabling of the dynamic scripting first. let's go

**Comment by karussell** [comment]
I could, yeah but ;)

dynamic scripting is done either in some external servers (if using transport addresses) or via the config you mean in the java code.

**Pull request merged**
