### PR TITLE
initial decompounder settings in separate analyser_de

### PR DESCRIPTION
**Pull request by karussell**
This fixes (partially) #42, is easy to understand and tweak.

### CODE REVIEW

**Comment by karussell** [comment]
For Germany this issue is very important to fix! 

If there is no slowdown for the import of other languages, couldn't we enable this just for all languages? Hmmh, I'll investigate also my last comment if we need this only for the query.

**Comment by hbruch** [comment]
@karussell As this PR is rather old, could you answer some questions? 

I assume that using language specific analyzers for name.lang and collector.lang would be ok, as @christophlingg mentioned, wouldn't it?

The [dictionary decompounder](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/analysis-compound-word-tokenfilter.html) came to my mind as well, but is supplying the common endings sufficient? Does it preserve the original term and/or the part preceding the ending? Looking into Lucene's [DictionaryCompoundWordTokenFilter](https://github.com/apache/lucene-solr/blob/master/lucene/analysis/common/src/java/org/apache/lucene/analysis/compound/DictionaryCompoundWordTokenFilter.java) I wonder, but perhaps I'm missing something(?)

Another option (though possibly not scaling to the number of subtokens you had in mind with this PR) could be to use a [Pattern Capture Token Filter](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/analysis-pattern-capture-tokenfilter.html).

Both solutions would require language specific patterns.

A rather language agnostic option might be to switch indexing/querying to ngrams (not just edge_ngrams). But this would result in some major indexing/querying changes and I'm not sure if it would improve overall matching, performance and which effects it had to index size.

**Comment by karussell** [comment]
Sorry do not know what the latest state is also we should add tests when adding it

**Comment by karussell** [comment]
Will be replaced soon.

**Pull request closed without merging**
